version: '3.8'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pushit
      - SPRING_DATASOURCE_USERNAME=pushit
      - SPRING_DATASOURCE_PASSWORD=pushit123

  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=pushit
      - POSTGRES_USER=pushit
      - POSTGRES_PASSWORD=pushit123